### ISSUE TITLE
Intents v2

### ISSUE THREAD

**Issue by pitasi** [warden-protocol/wardenprotocol#263]
Tracking issue for getting us to the v2 of our Intents engine.

~~- [ ] #259 for having actions that can be executed without further approvals when the conditions are met~~
- [x] #466 for retriggering Actions manually
- [x] #260 for being able to express price thresholds
- [x] #258 for referencing price values from within intents
- [x] #261 for being able to execute more complex actions (e.g. invoke smart contracts)
- [x] #262 for adding more data to intents
